name: checks
on: [pull_request, workflow_dispatch]

env:
  ACT_OWNER: ${{ github.repository_owner }}
  ACT_REPOSITORY: ${{ github.repository }}
  GO_VERSION: 1.17
  CGO_ENABLED: 0

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      - uses: megalinter/megalinter/flavors/go@v6.12.0
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          GITHUB_STATUS_REPORTER: ${{ !env.ACT }}
          GITHUB_COMMENT_REPORTER: ${{ !env.ACT }}

  test-linux:
    name: test-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go test -v -cover -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload Codecov report
        uses: codecov/codecov-action@v2.1.0
        with:
          files: coverage.txt
          fail_ci_if_error: true # optional (default = false)

  snapshot:
    name: snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v2
        if: ${{ !env.ACT }}
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --rm-dist
      - name: Capture x86_64 (64-bit) Linux binary
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: act-linux-amd64
          path: dist/act_linux_amd64/act
      - name: Capture i386 (32-bit) Linux binary
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: act-linux-i386
          path: dist/act_linux_386/act
      - name: Capture arm64 (64-bit) Linux binary
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: act-linux-arm64
          path: dist/act_linux_arm64/act
      - name: Capture armv6 (32-bit) Linux binary
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: act-linux-armv6
          path: dist/act_linux_arm_6/act
      - name: Capture armv7 (32-bit) Linux binary
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: act-linux-armv7
          path: dist/act_linux_arm_7/act
      - name: Capture x86_64 (64-bit) Windows binary
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: act-windows-amd64
          path: dist/act_windows_amd64/act.exe
      - name: Capture i386 (32-bit) Windows binary
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: act-windows-i386
          path: dist/act_windows_386/act.exe
      - name: Capture arm64 (64-bit) Windows binary
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: act-windows-arm64
          path: dist/act_windows_arm64/act.exe
      - name: Capture armv7 (32-bit) Windows binary
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: act-windows-armv7
          path: dist/act_windows_arm_7/act.exe
      - name: Capture x86_64 (64-bit) MacOS binary
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: act-macos-amd64
          path: dist/act_darwin_amd64/act
      - name: Capture arm64 (64-bit) MacOS binary
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v2
        with:
          name: act-macos-arm64
          path: dist/act_darwin_arm64/act
      - name: Chocolatey
        uses: ./.github/actions/choco
        with:
          version: v0.0.0-pr
